In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['figure.dpi'] = 150

from netam.common import print_parameter_count, pick_device

from netam import framework, models

from shmex.shm_data import train_val_dfs_of_nickname
from shmex.shm_zoo import default_burrito_params
from shmex.local import localify

figures_dir = localify('FIGURES_DIR')

device = pick_device()

GPU chosen via memory
Using CUDA GPU 1
GPU chosen via utilization
Using CUDA GPU 0

In [2]:
kmer_length = 3
site_count = 500
weight_decay = 1e-6

model_params = {
    "kmer_length": kmer_length,
    "kernel_size": 11,
    "embedding_dim": 6, # Slightly modified from `lrg` so that the embedding dimension is even (required for the positional encoding)
    "filter_count": 19,
    "dropout_prob": 0.3,
}

train_df, val_df = train_val_dfs_of_nickname('shmoof_small')

train_dataset = framework.SHMoofDataset(train_df, kmer_length=kmer_length, site_count=site_count)
val_dataset = framework.SHMoofDataset(val_df, kmer_length=kmer_length, site_count=site_count)

train_dataset.to(device)
val_dataset.to(device)

print(f"we have {len(train_dataset)} training examples and {len(val_dataset)} validation examples")

Interpreting shmoof_small as a shmoof dataset

we have 46391 training examples and 2625 validation examples

In [3]:
model = models.CNNPEModel(**model_params)
model.to(device)

burrito = framework.SHMBurrito(train_dataset, val_dataset, model, **default_burrito_params)
losses = burrito.simple_train(epochs=100)
losses.tail()

Epoch: 100%|██████████| 100/100 [01:52<00:00,  1.12s/it, loss_diff=-2.354e-06, lr=0.000125, val_loss=0.05559]

    train_loss  val_loss
95    0.062242  0.055594
96    0.062249  0.055596
97    0.062250  0.055594
98    0.062222  0.055592
99    0.062240  0.055590

For comparison, here's a simple CNN.

In [4]:
model = models.CNNModel(**model_params)
model.to(device)

burrito = framework.SHMBurrito(train_dataset, val_dataset, model, **default_burrito_params)
losses = burrito.simple_train(epochs=100)
losses.tail()

Epoch:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch: 100%|██████████| 100/100 [01:49<00:00,  1.10s/it, loss_diff=-1.003e-05, lr=0.0005, val_loss=0.05551]

    train_loss  val_loss
95    0.061196  0.055522
96    0.061193  0.055538
97    0.061221  0.055525
98    0.061185  0.055523
99    0.061206  0.055513